# ----------------------- #
#      Main Configs       #
# ----------------------- #

name: Andrea Mckenzie
url: http://ma3east.github.io/ || http://ma3east.com/
title: ma3east | The Personal Website for Andrea Mckenzie
author: 
  name: Andrea Mckenzie
  email: 
  twitter: ma3east
description: "This is the personal website for Andrea Mckenzie, a Full Stack Developer based in East London, UK."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:title.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ma3east
  - title: github
    url: https://github.com/ma3east
  - title: linkedin
    url: https://uk.linkedin.com/in/mckenzieandrea