# ----------------------- #
#      Main Configs       #
# ----------------------- #

name: Andrea Mckenzie
url: http://ma3east.com/ # http://ma3east.github.io/ 
title: ma3east | The Personal Website for Andrea Mckenzie
author: Andrea Mckenzie
description: "Welcome to ma3east.com, the website for budding Full Stack Developer Andrea Mckenzie, based in East London. Get in touch to discuss opportunities, I am keen to learn."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:title.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ma3east
  - title: github
    url: https://github.com/ma3east
  - title: linkedin
    url: https://uk.linkedin.com/in/mckenzieandrea

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.  

analytics :
      provider : google 
      google : 
          tracking_id : 'UA-68265403-1'

# Exclude these files from your production site
exclude:
  - LICENSE.md
  - README.md
  - CNAME

